apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-test-prod
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/quarkus-test/overlays/prod
    repoURL: https://github.com/cp1408/quarkus-test-gitops.git
    targetRevision: main
  destination:
    namespace: quarkus-test-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
