apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkus-test
  janus-idp.io/tekton: quarkus-test
  backstage.io/kubernetes-id: quarkus-test
  backstage.io/kubernetes-namespace: quarkus-test 
  app.kubernetes.io/part-of: quarkus-test
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
